---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
