---

# Sourced from https://github.com/geerlingguy/ansible-role-java/

os: linux

language: python
python:
  - "3.7"
cache: pip

services: docker

env:
  global:
    - ROLE_NAME: dotnet-core
  jobs:
    - MOLECULE_DISTRO='centos7' SDK_VERSION='2.1'
#    - MOLECULE_DISTRO='centos7' SDK_VERSION='2.2'
#    - MOLECULE_DISTRO='centos7' SDK_VERSION='3.0'
#
#    - MOLECULE_DISTRO='centos8' SDK_VERSION='2.1'
#    - MOLECULE_DISTRO='centos8' SDK_VERSION='2.2'
#    - MOLECULE_DISTRO='centos8' SDK_VERSION='3.0'
#
#    - MOLECULE_DISTRO='debian9' SDK_VERSION='2.1'
#    - MOLECULE_DISTRO='debian9' SDK_VERSION='2.2'
#    - MOLECULE_DISTRO='debian9' SDK_VERSION='3.0'
#
#    - MOLECULE_DISTRO='debian10' SDK_VERSION='2.1'
#    - MOLECULE_DISTRO='debian10' SDK_VERSION='2.2'
#    - MOLECULE_DISTRO='debian10' SDK_VERSION='3.0'
#
#    - MOLECULE_DISTRO='ubuntu1604' SDK_VERSION='2.1'
#    - MOLECULE_DISTRO='ubuntu1604' SDK_VERSION='2.2'
#    - MOLECULE_DISTRO='ubuntu1604' SDK_VERSION='3.0'
#
#    - MOLECULE_DISTRO='ubuntu1804' SDK_VERSION='2.1'
#    - MOLECULE_DISTRO='ubuntu1804' SDK_VERSION='2.2'
#    - MOLECULE_DISTRO='ubuntu1804' SDK_VERSION='3.0'
#
#    - MOLECULE_DISTRO='fedora31' SDK_VERSION='2.1'
#    - MOLECULE_DISTRO='fedora31' SDK_VERSION='2.2'
#    - MOLECULE_DISTRO='fedora31' SDK_VERSION='3.0'

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME rkm.$ROLE_NAME
  - cd rkm.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: change
    on_failure: change
