---

# Sourced from https://github.com/geerlingguy/ansible-role-java/

os: linux

language: python
python:
  - "3.7"
cache: pip

services: docker

env:
  global:
    - ROLE_NAME: dotnet_core
  jobs:
    - MOLECULE_DISTRO='centos:7' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='centos:7' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='centos:7' SDK_VERSION='3.0'

    - MOLECULE_DISTRO='centos:8' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='centos:8' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='centos:8' SDK_VERSION='3.0'

    - MOLECULE_DISTRO='debian:9' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='debian:9' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='debian:9' SDK_VERSION='3.0'

    - MOLECULE_DISTRO='debian:10' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='debian:10' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='debian:10' SDK_VERSION='3.0'

    - MOLECULE_DISTRO='ubuntu:16.04' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='ubuntu:16.04' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='ubuntu:16.04' SDK_VERSION='3.0'

    - MOLECULE_DISTRO='ubuntu:18.04' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='ubuntu:18.04' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='ubuntu:18.04' SDK_VERSION='3.0'

    - MOLECULE_DISTRO='ubuntu:19.04' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='ubuntu:19.04' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='ubuntu:19.04' SDK_VERSION='3.0'

    - MOLECULE_DISTRO='fedora:30' SDK_VERSION='2.1'
    - MOLECULE_DISTRO='fedora:30' SDK_VERSION='2.2'
    - MOLECULE_DISTRO='fedora:30' SDK_VERSION='3.0'

    # - MOLECULE_DISTRO='fedora:31' SDK_VERSION='2.1'
    # - MOLECULE_DISTRO='fedora:31' SDK_VERSION='2.2'
    # - MOLECULE_DISTRO='fedora:31' SDK_VERSION='3.0'

install:
  - pip install molecule docker

before_script:
  - cd ..
  - mv ansible-role-* rkm.$ROLE_NAME
  - cd rkm.$ROLE_NAME

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: change
    on_failure: change
