---

# Sourced from https://github.com/geerlingguy/ansible-role-java/

os: linux

language: python
python:
  - "3.7"

services: docker

env:
  global:
    - ROLE_NAME: dotnet-core
  jobs:
#    - MOLECULE_DISTRO: centos7
#    - MOLECULE_DISTRO: centos8
#    - MOLECULE_DISTRO: debian10
#    - MOLECULE_DISTRO: debian9
#    - MOLECULE_DISTRO: fedora31
#    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME rkm.$ROLE_NAME
  - cd rkm.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: change
    on_failure: change
