---

# yamllint disable
# https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-debian9
# https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-debian10
# yamllint enable

- name: Make sure HTTPS is supported by apt
  apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: Register Microsoft key & repo
  shell: |
    set -o pipefail
    wget -qO- {{ microsoft_key_url }} | gpg --dearmor > microsoft.asc.gpg
    mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
    wget -q https://packages.microsoft.com/config/\
    debian/{{ ansible_distribution_major_version }}/prod.list
    mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
    chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
    chown root:root /etc/apt/sources.list.d/microsoft-prod.list
  # NOTE: https://github.com/ansible/ansible-lint/issues/497
  args:
    executable: /bin/bash
  changed_when: false

- name: Apt update
  apt:
    update_cache: true
