---

# yamllint disable
# https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-centos7
# yamllint enable

- name: Add yum repository
  yum:
    name: "https://packages.microsoft.com/config/centos/7/\
          packages-microsoft-prod.rpm"
    state: present

- name: Update yum cache
  yum:
    state: present
    update_cache: true
