---

- name: Import Microsoft APT key
  apt_key:
    url: "{{ microsoft_key_url }}"
    state: present

- name: Download Microsoft repo
  get_url:
    url: https://packages.microsoft.com/config/fedora/30/prod.repo
    dest: /etc/yum.repos.d/microsoft-prod.repo

- name: Update dnf cache
  dnf:
    update_cache: true
