---

- name: Import Microsoft RPM key
  rpm_key:
    key: "{{ microsoft_key_url }}"
    state: present

- name: Download Microsoft repo
  get_url:
    url: "https://packages.microsoft.com/config/fedora/\
         {{ ansible_distribution_major_version }}/prod.repo"
    dest: /etc/yum.repos.d/microsoft-prod.repo

- name: Update dnf cache
  dnf:
    update_cache: true
