---

- include: rhel.yml
  when: ansible_distribution == 'CentOS'
        or ansible_distribution == 'Red Hat Enterprise Linux'
        or ansible_distribution == 'RedHat'
        or ansible_distribution == 'Amazon'

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Detect TravisCI
  set_fact:
    is_travis: "{{ lookup('env', 'TRAVIS') | bool }}"

- name: Debug
  debug:
    msg: Is Travis? {{ is_travis }}

# TODO Set sdk_version

- name: Install dotnet core
  package:
    name: "{{ sdk_version }}"
    state: present
    update_cache: true
