---

- name: Install gpg
  package:
    name: gpg
    state: present
  failed_when: false

- name: Include debian.yml
  include: debian.yml
  when: ansible_distribution == 'Debian'

- name: Include el.yml
  include: el.yml
  when: >
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'RedHat' or
    ansible_distribution == 'Amazon'

- name: Include ubuntu.yml
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include fedora.yml
  include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Determine SDK version
  set_fact:
    _sdk_version: "{{ dotnet_package }}"
  when: _sdk_version is not defined

- name: Install dotnet core SDK
  package:
    name: dotnet-sdk-{{ _sdk_version }}
    state: present
    update_cache: true
