---

- name: Include debian.yml
  include: debian.yml
  when: ansible_distribution == 'Debian'

- name: Include centos.yml
  include: rhel.yml
  when: ansible_distribution == 'CentOS'

- name: Include centos.yml
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Detect TravisCI
  set_fact:
    is_travis: "{{ lookup('env', 'TRAVIS') | bool }}"

- name: Set SDK version
  set_fact:
    sdk_version: >-
      {% if is_travis -%}{{ lookup('env', 'SDK_VERSION') }}
      {%- else -%}{{ dotnet_package }}
      {%- endif %}

- name: Install dotnet core SDK
  package:
    name: dotnet-sdk-{{ sdk_version }}
    state: present
    update_cache: true
