---

- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: rkm.dotnet-core
  post_tasks:
    - name: Check dotnet version
      command: dotnet --version
      register: result
      failed_when: result.rc != 0 or {{ sdk_version }} not in result.stdout
