---

- name: Converge
  hosts: all
  pre_tasks:
    - name: Set SDK version
      set_fact:
        _sdk_version: "{{ lookup('env', 'SDK_VERSION') }}"
    - name: Install python
      package:
        name: python
        state: present
  roles:
    - role: rkm.dotnet_core
  post_tasks:
    - name: Check dotnet version
      command: dotnet --version
      register: result
      failed_when: _sdk_version not in result.stdout
      changed_when: false
